### ISSUE TITLE
Startup error on TacoSpigot

### ISSUE THREAD

**Issue by T1MOXA** [RockinChaos/ItemJoin#108]
```
[01:33:23] [Server thread/ERROR]: Error occurred while enabling ItemJoin v3.9.3 (Is it up to date?)
java.lang.NoClassDefFoundError: org/bukkit/craftbukkit/libs/jline/internal/InputStreamReader
	at me.RockinChaos.itemjoin.ItemJoin.onEnable(ItemJoin.java:50) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[patched.jar:git-TacoSpigot-"22b1d457"]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316) [patched.jar:git-TacoSpigot-"22b1d457"]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404) [patched.jar:git-TacoSpigot-"22b1d457"]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:378) [patched.jar:git-TacoSpigot-"22b1d457"]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:328) [patched.jar:git-TacoSpigot-"22b1d457"]
	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:441) [patched.jar:git-TacoSpigot-"22b1d457"]
	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:402) [patched.jar:git-TacoSpigot-"22b1d457"]
	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:340) [patched.jar:git-TacoSpigot-"22b1d457"]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:290) [patched.jar:git-TacoSpigot-"22b1d457"]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:615) [patched.jar:git-TacoSpigot-"22b1d457"]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
Caused by: java.lang.ClassNotFoundException: org.bukkit.craftbukkit.libs.jline.internal.InputStreamReader
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:92) ~[patched.jar:git-TacoSpigot-"22b1d457"]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:87) ~[patched.jar:git-TacoSpigot-"22b1d457"]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_121]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_121]
	... 12 more
[01:33:23] [Server thread/INFO]: [ItemJoin] Disabling ItemJoin v3.9.3
[01:33:23] [Server thread/ERROR]: Error occurred while disabling ItemJoin v3.9.3 (Is it up to date?)
java.lang.NoClassDefFoundError: org/bukkit/craftbukkit/libs/jline/internal/InputStreamReader
	at me.RockinChaos.itemjoin.ItemJoin.onDisable(ItemJoin.java:63) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[patched.jar:git-TacoSpigot-"22b1d457"]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:344) [patched.jar:git-TacoSpigot-"22b1d457"]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:320) [patched.jar:git-TacoSpigot-"22b1d457"]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404) [patched.jar:git-TacoSpigot-"22b1d457"]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:378) [patched.jar:git-TacoSpigot-"22b1d457"]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:328) [patched.jar:git-TacoSpigot-"22b1d457"]
	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:441) [patched.jar:git-TacoSpigot-"22b1d457"]
	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:402) [patched.jar:git-TacoSpigot-"22b1d457"]
	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:340) [patched.jar:git-TacoSpigot-"22b1d457"]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:290) [patched.jar:git-TacoSpigot-"22b1d457"]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:615) [patched.jar:git-TacoSpigot-"22b1d457"]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
Caused by: java.lang.ClassNotFoundException: org.bukkit.craftbukkit.libs.jline.internal.InputStreamReader
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:92) ~[patched.jar:git-TacoSpigot-"22b1d457"]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:87) ~[patched.jar:git-TacoSpigot-"22b1d457"]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_121]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_121]
	... 13 more
```

**Comment by RockinChaos** [comment]
Issue is resolved in v4.0 and it will be released in the next week or you can download the snapshot for v3.9.4 which fixes this issue; http://jenkins.craftationgaming.com:8080/job/ItemJoin/5/artifact/target/ItemJoin-3.9.4-SNAPSHOT.jar

**Comment by T1MOXA** [comment]
I understand in that 4.0 is still not fixed ?
I just downloaded the latest build, and it is also have a bug, but truth is different.
```
[Server thread/ERROR]: Could not pass event PlayerJoinEvent to ItemJoin v4.0.0-SNAPSHOT
org.bukkit.event.EventException: null
	at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:46) ~[patched.jar:git-TacoSpigot-"22b1d457"]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched.jar:git-TacoSpigot-"22b1d457"]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched.jar:git-TacoSpigot-"22b1d457"]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:514) [patched.jar:git-TacoSpigot-"22b1d457"]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:499) [patched.jar:git-TacoSpigot-"22b1d457"]
	at net.minecraft.server.v1_12_R1.PlayerList.onPlayerJoin(PlayerList.java:366) [patched.jar:git-TacoSpigot-"22b1d457"]
	at net.minecraft.server.v1_12_R1.PlayerList.a(PlayerList.java:179) [patched.jar:git-TacoSpigot-"22b1d457"]
	at protocolsupport.zplatform.impl.spigot.network.handler.SpigotLoginListenerPlay.joinGame(SpigotLoginListenerPlay.java:124) [ProtocolSupport.jar:?]
	at protocolsupport.protocol.packet.handler.AbstractLoginListenerPlay.tryJoin(AbstractLoginListenerPlay.java:112) [ProtocolSupport.jar:?]
	at protocolsupport.protocol.packet.handler.AbstractLoginListenerPlay.tick(AbstractLoginListenerPlay.java:71) [ProtocolSupport.jar:?]
	at protocolsupport.zplatform.impl.spigot.network.handler.SpigotLoginListenerPlay.e(SpigotLoginListenerPlay.java:70) [ProtocolSupport.jar:?]
	at net.minecraft.server.v1_12_R1.NetworkManager.a(NetworkManager.java:202) [patched.jar:git-TacoSpigot-"22b1d457"]
	at net.minecraft.server.v1_12_R1.ServerConnection.c(ServerConnection.java:150) [patched.jar:git-TacoSpigot-"22b1d457"]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:937) [patched.jar:git-TacoSpigot-"22b1d457"]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) [patched.jar:git-TacoSpigot-"22b1d457"]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:766) [patched.jar:git-TacoSpigot-"22b1d457"]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:664) [patched.jar:git-TacoSpigot-"22b1d457"]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
Caused by: java.lang.NullPointerException
	at me.RockinChaos.itemjoin.cacheitems.CreateItems.setMapImage(CreateItems.java:383) ~[?:?]
	at me.RockinChaos.itemjoin.cacheitems.CreateItems.run(CreateItems.java:65) ~[?:?]
	at me.RockinChaos.itemjoin.listeners.giveitems.PlayerJoin.setItems(PlayerJoin.java:48) ~[?:?]
	at me.RockinChaos.itemjoin.listeners.giveitems.PlayerJoin.giveOnJoin(PlayerJoin.java:30) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor139.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:44) ~[patched.jar:git-TacoSpigot-"22b1d457"]
	... 17 more
```

**Comment by RockinChaos** [comment]
v4.0 isnt released yet I said to download the link I sent you.

**Comment by T1MOXA** [comment]
I know, but I was curious )

**Comment by RockinChaos** [comment]
Yeah theres an issue with maps in v4.0 I have been working on. Its disabled for bug testers until I fix it.

**Comment by T1MOXA** [comment]
No, all good, thank you )

**Comment by T1MOXA** [comment]
Although there is one error...
```
[ItemJoin] Task #6258 for ItemJoin v3.9.4-SNAPSHOT generated an exception
java.lang.NoClassDefFoundError: fr/xephi/authme/api/API
	at me.RockinChaos.itemjoin.Listeners.JoinItem.JoinItem$1.run(JoinItem.java:49) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:58) ~[patched.jar:git-TacoSpigot-"22b1d457"]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:356) [patched.jar:git-TacoSpigot-"22b1d457"]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:832) [patched.jar:git-TacoSpigot-"22b1d457"]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) [patched.jar:git-TacoSpigot-"22b1d457"]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:766) [patched.jar:git-TacoSpigot-"22b1d457"]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:664) [patched.jar:git-TacoSpigot-"22b1d457"]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
[ItemJoin] Task #6258 for ItemJoin v3.9.4-SNAPSHOT generated an exception
java.lang.NoClassDefFoundError: fr/xephi/authme/api/API
	at me.RockinChaos.itemjoin.Listeners.JoinItem.JoinItem$1.run(JoinItem.java:49) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:58) ~[patched.jar:git-TacoSpigot-"22b1d457"]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:356) [patched.jar:git-TacoSpigot-"22b1d457"]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:832) [patched.jar:git-TacoSpigot-"22b1d457"]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) [patched.jar:git-TacoSpigot-"22b1d457"]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:766) [patched.jar:git-TacoSpigot-"22b1d457"]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:664) [patched.jar:git-TacoSpigot-"22b1d457"]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
```

**Comment by RockinChaos** [comment]
If you dont have AuthMe keep it set to false in the config.yml It looks like it was toggled on.

**Comment by T1MOXA** [comment]
I have AuthMe, and I set it to true

**Comment by RockinChaos** [comment]
and you are receiving that error with authme enabled?

**Comment by T1MOXA** [comment]
In the sense what plugin boot first?

**Comment by RockinChaos** [comment]
I figured out what your issue is. AuthMe changed their API without telling us. Ill have a working snapshot in a few minutes.

**Comment by RockinChaos** [comment]
Sorry about the confusion It has been fixed, I had no idea that AuthMe's api had changed.

You can download it here; https://www.dropbox.com/s/2fmw638j44sw4eh/ItemJoin-3.9.4-SNAPSHOT.jar?dl=0

**Comment by T1MOXA** [comment]
Everything seems to be OK

**Comment by RockinChaos** [comment]
Sweet let me know if you need help with anything else.
