### ISSUE TITLE
Items Not working

### ISSUE THREAD

**Issue by evanmcclan** [RockinChaos/ItemJoin#171]
**ItemJoin Version:** 4.7
**Server version:** This server is running CraftBukkit version git-Spigot-5695bca-53fccdf (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

**Problem:** Items that are configured to not be able to have inventory movement can be remved from/ moved around a players inventory. Players are also able to drop these items usind the minecraft drop hotkey even when items are flagged not to drop. 

My second problem is that some items are not performing their commands properly. Items that are configured to open a CustomGUI menu for some reason are spammed many times. (This is not an issue with customgui). The problem that the spam creates is that it tries opening the menu so many times that it times out the customgui plugin. (this bug shows no errors in console except the response from custom gui getting spammed)

Other problems ive been having with the plugin is that some of the itemJoin commands throw errors when trying to run them in console. My main problem is with `ItemJoin get <Item> <Player>`

**Error it shows for IJ Get from console**: https://pastebin.com/1VxEyptN

**Plugin Config**: https://pastebin.com/vKPQGZh0

ItemsYML File**: https://pastebin.com/tWQMdxKv

**Comment by RockinChaos** [comment]
These issues were resolved a few weeks ago in the latest snapshot. This one is safe to use and should resolve your problems until the full release of v4.8 is ready.

Let me know!
Get it here; http://ci.craftationgaming.com/job/ItemJoin/107/

**Comment by evanmcclan** [comment]
@RockinChaos The error is still happening on the snapshot you linked me to
https://pastebin.com/cwQPEF0B

**Comment by RockinChaos** [comment]
Can you send me your en-lang.yml in a pastebin link please, something isn't right.

**Comment by evanmcclan** [comment]
Here it is, https://pastebin.com/cLYjvKDV (i found that renaming some of the items stops the bug. For example, i have items Magicband and magicband2-14. 2-14 dont spam the commands, but naiming an item magicband or magicband1 causes the spam

**Comment by evanmcclan** [comment]
Update: any item flagged to trigger on join, respawn, and world-change spams the command most of the time

**Comment by RockinChaos** [comment]
Ahh wait I think I know what it is, can you add 

`NewNBT-System: true`

To the config.yml below the helditem-slot. Then try clearing your inventory and see if this issue persists. This is because in the snapshot I added an nbt tag to fix these issues but you are missing the option from config.yml. Also note this issue exists because each of the items have the same item id 402. Thats why I added the additional nbt tag.

**Comment by evanmcclan** [comment]
That fixed it. Thankyou 👍

**Comment by RockinChaos** [comment]
Sweet sorry it took so long for me to notice. Let me know if you need help with anything else, I am always around!
