### ISSUE TITLE
Problem with PlayerJoinEvent 

### ISSUE THREAD

**Issue by afronights** [RockinChaos/ItemJoin#33]
I've tried with 1.8.8 and 1.9.2 servers ( {"spigot-1.8.8-R0.1-SNAPSHOT" - 18,8 MB}, {"spigot-1.9.2" - 19,5 MB } ), but i encountered the same problem:
  [ERROR] Could not pass event PlayerJoinEvent to ItemJoin v2.9

Can you help me ?

   Thank you Andrea Tribuiani

**Comment by RockinChaos** [comment]
First try using the newest version of spigot compiled by buildtools. There has been some bugs with spigot lately. 

Second, can you send me the full ERROR? I cannot get anything off of just a notice. I need the java lines outputs.

Third, Please post your config and items.yml into pastebin.com and link them to me.

**Comment by AngryJebus** [comment]
I have the same issue on my Bukkit 1.9.2 server, whenever someone joins this message is put into the console:

[21:21:38] [Server thread/ERROR]: Could not pass event PlayerJoinEvent to ItemJoin v2.9
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[minecraft_server.jar:git-Bukkit-7fc5cd8]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[minecraft_server.jar:git-Bukkit-7fc5cd8]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:501) [minecraft_server.jar:git-Bukkit-7fc5cd8]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:486) [minecraft_server.jar:git-Bukkit-7fc5cd8]
	at net.minecraft.server.v1_9_R1.PlayerList.onPlayerJoin(PlayerList.java:316) [minecraft_server.jar:git-Bukkit-7fc5cd8]
	at net.minecraft.server.v1_9_R1.PlayerList.a(PlayerList.java:143) [minecraft_server.jar:git-Bukkit-7fc5cd8]
	at net.minecraft.server.v1_9_R1.LoginListener.b(LoginListener.java:115) [minecraft_server.jar:git-Bukkit-7fc5cd8]
	at net.minecraft.server.v1_9_R1.LoginListener.c(LoginListener.java:53) [minecraft_server.jar:git-Bukkit-7fc5cd8]
	at net.minecraft.server.v1_9_R1.NetworkManager.a(NetworkManager.java:223) [minecraft_server.jar:git-Bukkit-7fc5cd8]
	at net.minecraft.server.v1_9_R1.ServerConnection.c(SourceFile:187) [minecraft_server.jar:git-Bukkit-7fc5cd8]
	at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:751) [minecraft_server.jar:git-Bukkit-7fc5cd8]
	at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:361) [minecraft_server.jar:git-Bukkit-7fc5cd8]
	at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:635) [minecraft_server.jar:git-Bukkit-7fc5cd8]
	at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:539) [minecraft_server.jar:git-Bukkit-7fc5cd8]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
Caused by: java.lang.NullPointerException
	at me.RockinChaos.itemjoin.utils.CheckItem.CheckMaterial(CheckItem.java:123) ~[?:?]
	at me.RockinChaos.itemjoin.ItemJoin.CacheItems(ItemJoin.java:130) ~[?:?]
	at me.RockinChaos.itemjoin.Listeners.JoinItem.JoinItem.giveOnJoin(JoinItem.java:45) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_91]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_91]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_91]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_91]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300) ~[minecraft_server.jar:git-Bukkit-7fc5cd8]
	... 14 more

**Comment by RockinChaos** [comment]
Can you guys try the 3.0-SNAPSHOT and let me know if this fixes your problems;
https://www.mediafire.com/?bf6ee5qbq35bqbs

Also do these errors prevent you from getting the items or is it just spamming console?

**Comment by AngryJebus** [comment]
Hi, thanks for releasing that! It works and players are now receiving the items. Thank you so much!!! Awesome plugin!!!

(Before, the players never received the items, and the previous error code was only put into chat whenever a player joined the server)

Thanks!

**Comment by karelzak** [comment]
Still have problems with 3.0-SNAPSHOT, spigot rebuilt a few minutes ago,

[21:53:46 INFO]: Starting minecraft server version 1.9.2
[21:53:46 INFO]: Loading properties
[21:53:46 INFO]: Default game type: SURVIVAL
[21:53:46 INFO]: This server is running CraftBukkit version git-Spigot-e6f93f4-ed60c01 (MC: 1.9.2) (Implementing API version 1.9.2-R0.1-SNAPSHOT)

....

[21:53:49 INFO]: [ItemJoin] Enabling ItemJoin v3.0-SNAPSHOT
[21:53:49 INFO]: [ItemJoin] Hooked into Multiverse-Core!
[21:53:49 INFO]: [ItemJoin] Cached creative
[21:53:49 INFO]: [ItemJoin] Checking for updates...
[21:53:50 INFO]: [ItemJoin] You are running a SNAPSHOT!
[21:53:50 INFO]: [ItemJoin] If you find any bugs please report them!
[21:53:50 INFO]: [ItemJoin] You are up to date!
[21:53:50 INFO]: [ItemJoin] has been Enabled!

...

[21:54:03 ERROR]: Could not pass event PlayerJoinEvent to ItemJoin v3.0-SNAPSHOT
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-1.9.2.jar:git-Spigot-e6f93f4-ed60c01]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.9.2.jar:git-Spigot-e6f93f4-ed60c01]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.9.2.jar:git-Spigot-e6f93f4-ed60c01]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.9.2.jar:git-Spigot-e6f93f4-ed60c01]
	at net.minecraft.server.v1_9_R1.PlayerList.onPlayerJoin(PlayerList.java:332) [spigot-1.9.2.jar:git-Spigot-e6f93f4-ed60c01]
	at net.minecraft.server.v1_9_R1.PlayerList.a(PlayerList.java:158) [spigot-1.9.2.jar:git-Spigot-e6f93f4-ed60c01]
	at net.minecraft.server.v1_9_R1.LoginListener.b(LoginListener.java:144) [spigot-1.9.2.jar:git-Spigot-e6f93f4-ed60c01]
	at net.minecraft.server.v1_9_R1.LoginListener.c(LoginListener.java:54) [spigot-1.9.2.jar:git-Spigot-e6f93f4-ed60c01]
	at net.minecraft.server.v1_9_R1.NetworkManager.a(NetworkManager.java:232) [spigot-1.9.2.jar:git-Spigot-e6f93f4-ed60c01]
	at net.minecraft.server.v1_9_R1.ServerConnection.c(ServerConnection.java:141) [spigot-1.9.2.jar:git-Spigot-e6f93f4-ed60c01]
	at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:820) [spigot-1.9.2.jar:git-Spigot-e6f93f4-ed60c01]
	at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot-1.9.2.jar:git-Spigot-e6f93f4-ed60c01]
	at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660) [spigot-1.9.2.jar:git-Spigot-e6f93f4-ed60c01]
	at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559) [spigot-1.9.2.jar:git-Spigot-e6f93f4-ed60c01]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
Caused by: java.lang.NullPointerException
	at me.RockinChaos.itemjoin.ItemJoin.CacheItems(ItemJoin.java:199) ~[?:?]
	at me.RockinChaos.itemjoin.Listeners.JoinItem.JoinItem.giveOnJoin(JoinItem.java:45) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_91]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_91]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_91]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_91]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.9.2.jar:git-Spigot-e6f93f4-ed60c01]
	... 14 more
[21:54:03 INFO]: lerakkaz[/127.0.0.1:46982] logged in with entity id 526 at ([creative]-44.40682813858574, 64.0, 236.2999302301006)

**Comment by RockinChaos** [comment]
I have figured out this has to do with the new map rendering added to ItemJoin. I believe I have fixed this, I am unable to reproduce these errors so if you could please test it and let me know if everything works.

https://www.mediafire.com/?5uwcd73vp3e2pno

**Comment by karelzak** [comment]
Still the same, I have also tried fresh spigot installation without another modules and still get the exception.

[00:04:51 ERROR]: Could not pass event PlayerJoinEvent to ItemJoin v3.0-SNAPSHOT
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-1.9.2.jar:git-Spigot-e6f93f4-ed60c01]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.9.2.jar:git-Spigot-e6f93f4-ed60c01]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.9.2.jar:git-Spigot-e6f93f4-ed60c01]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.9.2.jar:git-Spigot-e6f93f4-ed60c01]
	at net.minecraft.server.v1_9_R1.PlayerList.onPlayerJoin(PlayerList.java:332) [spigot-1.9.2.jar:git-Spigot-e6f93f4-ed60c01]
	at net.minecraft.server.v1_9_R1.PlayerList.a(PlayerList.java:158) [spigot-1.9.2.jar:git-Spigot-e6f93f4-ed60c01]
	at net.minecraft.server.v1_9_R1.LoginListener.b(LoginListener.java:144) [spigot-1.9.2.jar:git-Spigot-e6f93f4-ed60c01]
	at net.minecraft.server.v1_9_R1.LoginListener.c(LoginListener.java:54) [spigot-1.9.2.jar:git-Spigot-e6f93f4-ed60c01]
	at net.minecraft.server.v1_9_R1.NetworkManager.a(NetworkManager.java:232) [spigot-1.9.2.jar:git-Spigot-e6f93f4-ed60c01]
	at net.minecraft.server.v1_9_R1.ServerConnection.c(ServerConnection.java:141) [spigot-1.9.2.jar:git-Spigot-e6f93f4-ed60c01]
	at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:820) [spigot-1.9.2.jar:git-Spigot-e6f93f4-ed60c01]
	at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot-1.9.2.jar:git-Spigot-e6f93f4-ed60c01]
	at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660) [spigot-1.9.2.jar:git-Spigot-e6f93f4-ed60c01]
	at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559) [spigot-1.9.2.jar:git-Spigot-e6f93f4-ed60c01]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
Caused by: java.lang.NullPointerException
	at me.RockinChaos.itemjoin.ItemJoin.CacheItems(ItemJoin.java:199) ~[?:?]
	at me.RockinChaos.itemjoin.Listeners.JoinItem.JoinItem.giveOnJoin(JoinItem.java:45) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_91]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_91]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_91]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_91]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.9.2.jar:git-Spigot-e6f93f4-ed60c01]

**Comment by RockinChaos** [comment]
Try this:

https://www.mediafire.com/?ykzeaqga33396qv

**Comment by karelzak** [comment]
Congratulation :-) Fixed, works as expected.

**Comment by RockinChaos** [comment]
v3.0 has been uploaded and will be approved shortly! This addresses these issues.
