### ISSUE TITLE
It gives an error after deleting the item I added

### ISSUE THREAD

**Issue by TeQTabanca** [RockinChaos/ItemJoin#469]
**Describe the bug**
It gives different errors after deleting the item I added

**To Reproduce**
1. İ am creating item
2. I'm deleting the item

**Expected behavior**
After deleting the item, it should not give an error.

**Errors**
```
[17:01:59 WARN]: [ItemJoin] Plugin ItemJoin v5.2.4-SNAPSHOT-b810 generated an exception while executing task 264645
java.lang.NullPointerException: null
        at me.RockinChaos.itemjoin.utils.interfaces.menus.Menu.setButton(Menu.java:436) ~[ItemJoin-5.2.4-SNAPSHOT-b810.jar:?]
        at me.RockinChaos.itemjoin.utils.interfaces.menus.Menu.setPage(Menu.java:532) ~[ItemJoin-5.2.4-SNAPSHOT-b810.jar:?]
        at me.RockinChaos.itemjoin.utils.interfaces.menus.Menu.lambda$startModify$50(Menu.java:355) ~[ItemJoin-5.2.4-SNAPSHOT-b810.jar:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76) ~[server.jar:git-Spigot-79a30d7-acbc348]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [server.jar:git-Spigot-79a30d7-acbc348]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:829) [?:?]

[17:09:21 ERROR]: Could not pass event InventoryClickEvent to ItemJoin v5.2.4-SNAPSHOT-b810
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[server.jar:git-Spigot-79a30d7-acbc348]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[server.jar:git-Spigot-79a30d7-acbc348]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [server.jar:git-Spigot-79a30d7-acbc348]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [server.jar:git-Spigot-79a30d7-acbc348]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1893) [server.jar:git-Spigot-79a30d7-acbc348]
        at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:33) [server.jar:git-Spigot-79a30d7-acbc348]
        at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:10) [server.jar:git-Spigot-79a30d7-acbc348]
        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [server.jar:git-Spigot-79a30d7-acbc348]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [server.jar:git-Spigot-79a30d7-acbc348]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [server.jar:git-Spigot-79a30d7-acbc348]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [server.jar:git-Spigot-79a30d7-acbc348]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [server.jar:git-Spigot-79a30d7-acbc348]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [server.jar:git-Spigot-79a30d7-acbc348]
        at java.lang.Thread.run(Thread.java:829) [?:?]
Caused by: java.lang.IndexOutOfBoundsException: Index 6 out of bounds for length 6
        at jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64) ~[?:?]
        at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70) ~[?:?]
        at jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248) ~[?:?]
        at java.util.Objects.checkIndex(Objects.java:372) ~[?:?]
        at java.util.ArrayList.get(ArrayList.java:459) ~[?:?]
        at me.RockinChaos.itemjoin.utils.interfaces.Page.chatEvent(Page.java:132) ~[ItemJoin-5.2.4-SNAPSHOT-b810.jar:?]
        at me.RockinChaos.itemjoin.utils.interfaces.Interface.onClick(Interface.java:99) ~[ItemJoin-5.2.4-SNAPSHOT-b810.jar:?]
        at me.RockinChaos.itemjoin.listeners.Interfaces.onClick(Interfaces.java:48) ~[ItemJoin-5.2.4-SNAPSHOT-b810.jar:?]
        at jdk.internal.reflect.GeneratedMethodAccessor262.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[server.jar:git-Spigot-79a30d7-acbc348]
        ... 15 more
```

**Please complete the following information:**
 - Resource Version and Build Number: [5.2.4-b810]
 - Server Version [Spigot-1.12.2]

**Comment by TeQTabanca** [comment]
**This error seems to take some time to fix. Because every time I delete an item, a different version of the error appears.**

**Comment by TeQTabanca** [comment]
### I downloaded the latest version but when the server is up and I add an item this error pops up.

```
[15:13:02 INFO]: [ItemJoin] 24 Custom item(s) loaded!
[15:13:02 ERROR]: [ItemJoin] Plugin ItemJoin v5.2.4-SNAPSHOT-b815 has failed to register events for class me.RockinChaos.itemjoin.listeners.plugins.ChestSortAPI because de/jeff_media/chestsort/api/ChestSortEvent does not exist.
```

**Minecraft 1.12.2 servers can use version 9.5.1 of chestsort.
Because the author of chestsort works for 1.16 and above.**

### Finally, if I enter the arbitrary section and press the space next to the last item, it gives an error.

```
[15:14:59 ERROR]: Could not pass event InventoryClickEvent to ItemJoin v5.2.4-SNAPSHOT-b815
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[server.jar:git-Spigot-79a30d7-acbc348]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[server.jar:git-Spigot-79a30d7-acbc348]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [server.jar:git-Spigot-79a30d7-acbc348]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [server.jar:git-Spigot-79a30d7-acbc348]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1893) [server.jar:git-Spigot-79a30d7-acbc348]
        at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:33) [server.jar:git-Spigot-79a30d7-acbc348]
        at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:10) [server.jar:git-Spigot-79a30d7-acbc348]
        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [server.jar:git-Spigot-79a30d7-acbc348]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [server.jar:git-Spigot-79a30d7-acbc348]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [server.jar:git-Spigot-79a30d7-acbc348]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [server.jar:git-Spigot-79a30d7-acbc348]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [server.jar:git-Spigot-79a30d7-acbc348]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [server.jar:git-Spigot-79a30d7-acbc348]
        at java.lang.Thread.run(Thread.java:829) [?:?]
Caused by: java.lang.IndexOutOfBoundsException: Index 6 out of bounds for length 6
        at jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64) ~[?:?]
        at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70) ~[?:?]
        at jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248) ~[?:?]
        at java.util.Objects.checkIndex(Objects.java:372) ~[?:?]
        at java.util.ArrayList.get(ArrayList.java:459) ~[?:?]
        at me.RockinChaos.itemjoin.utils.interfaces.Page.chatEvent(Page.java:132) ~[ItemJoin-5.2.4-SNAPSHOT-b815.jar:?]
        at me.RockinChaos.itemjoin.utils.interfaces.Interface.onClick(Interface.java:99) ~[ItemJoin-5.2.4-SNAPSHOT-b815.jar:?]
        at me.RockinChaos.itemjoin.listeners.Interfaces.onClick(Interfaces.java:48) ~[ItemJoin-5.2.4-SNAPSHOT-b815.jar:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[server.jar:git-Spigot-79a30d7-acbc348]
        ... 15 more
```

**Comment by RockinChaos** [comment]
Confirmed both issues, should now be resolved in the latest snapshot.

Link; https://ci.craftationgaming.com/job/ItemJoin/820/
**Remember to remove your old ItemJoin.jar file**

Let me know!~

**Comment by TeQTabanca** [comment]
There is an bug with "ChestSort".

https://user-images.githubusercontent.com/89253304/164886420-c0ff693a-110f-4671-bcd8-902ca7a26360.mp4

Finally, the stackable flag doesn't work at all. I tried it on the diamond sword, but it doesn't stack. If I give a stack with the "/itemjoin get" command, the item is separated when I click on it.


https://user-images.githubusercontent.com/89253304/164886873-9e299ab8-2637-4182-9cf4-1ec22a885ec8.mp4

**Comment by RockinChaos** [comment]
I sincerely apologize for the delayed reply, this took a bit of time to fix.
1.) Should now be fixed in the latest snapshot.
2.) So I was able to replicate the stackable issue and it only occurs in creative mode. Creative mode is a really awful system. Events and such do not always work as they should and are pretty much unfixable so I have to implement my own fixes to resolve a Minecraft/Microsoft problem. In this case, it is **NOT** possible to fix as creative mode does not trigger properly only handling items client-side. I have implemented some changes to block creative mode stacking for stackable items to hopefully retain how they are without breaking them until the user enters survival again. If you are interested in alternatives, a plugin called [FakeCreative](https://www.spigotmc.org/resources/fakecreative.95959/) has the same functionality as creative mode but actually functions properly since the user is statistically in survival but is granted creative functionality. It has freely available dev-builds to use if you want to check it out.

I apologize as this is likely not the outcome you want but unfortunately a lot of Minecraft code is garbage and is unmaintained by the developers. Creative mode just happens to be the worst in that category. If you do a quick google search you will notice all stackable plugins do not support creative mode due to these issues.

Link; https://ci.craftationgaming.com/job/ItemJoin/821/
**Remember to remove your old ItemJoin.jar file**

Let me know!~

**Comment by TeQTabanca** [comment]
**I tried the new version, but the "chestsort" error still persists. Finally, I tried in survival mode to stack items. But this time it stacks, but if the item is stacked, I cannot add all of that item to another slot, I have to add it one by one.**

https://user-images.githubusercontent.com/89253304/166915969-8de4b616-3191-428b-bcd8-afd12e1ee87c.mp4


https://user-images.githubusercontent.com/89253304/166915987-ad8f18a3-a1e8-4a55-b3ea-c949f0ce3602.mp4

**Comment by RockinChaos** [comment]
Can you send me the exact item you are using for stackable so I can test it. I can't seem to replicate this behavior with my item so it might be specific to yours.

**Comment by TeQTabanca** [comment]
```
  item_1:
    id: DIAMOND_SWORD
    itemflags: STACKABLE
```

**Comment by TeQTabanca** [comment]
**The "StackableItems" plugin was preventing me from putting the stacked item elsewhere. It was fixed when I deleted the plugin, but I need that plugin as well. I can use the 1.0.5 version of the plugin. Because its author is updating 1.17 and above.**

**Comment by RockinChaos** [comment]
Okay so I spent a long time on the stackable issue and I can confirm there is nothing ItemJoin can do to stop Stackable from managing an ItemJoin item.

My suggestion is to open a feature request with the Stackable developer and request API implementation to block the Stackable plugin from handling the InventoryClickEvent/InventoryDragEvent for a specific item if it is bypassed by another plugin. Like whitelisting an item at the time of interaction.

As for the ChestSort issue I am no longer able to replicate what you are showing in the b821 snapshot I linked above, can you confirm that you are running b821 via `/itemjoin` will show the build number.

If you are using b821, what exactly are you doing to produce this issue? Steps + Keycombinations would help immensely.

**Comment by TeQTabanca** [comment]
**Even if I want a feature for the "StackableItems" plugin, the plugin cannot be opened because my server version is low. I have already stated above. It would be nice if you could make one like the "StackableItems" plugin. Because there are very few authors who make such plugins.**

https://user-images.githubusercontent.com/89253304/167488446-aa70b805-98d0-4c37-9679-4b2d263a041d.mp4

**Comment by TeQTabanca** [comment]
**It's been a long time, but there is one more problem, I updated to b-829, but when I try to adjust the items I previously set in this version, the gui refreshes itself and you need to close the game completely to close it. Another mistake is that normal players cannot put their armor items in a different slot and they cannot remove them when they wear them. If he puts the player in creative mode, he can remove them and put them in a different slot.**

https://user-images.githubusercontent.com/89253304/171672316-14cde0a4-bb9c-44ed-89c3-e1b21b38fa19.mp4


https://user-images.githubusercontent.com/89253304/171672339-a7424199-82f0-4d0e-9971-c2f3685d8269.mp4

**Comment by RockinChaos** [comment]
I sincerely apologize for the delayed reply, I did not see the previous message from 27 days ago.
I don't often check GitHub as it doesn't see as much activity as the Discord Server does for support so I again apologize for taking a few days to see your latest message.

I am looking into this now and will provide you with some insight shortly.

**Comment by TeQTabanca** [comment]
**I solved the problem of not being able to move armor items. It happens because I set the properties in the "Prevent" section to true.**

**Comment by TeQTabanca** [comment]
**additionally use this items.yml file to understand gui self refresh issue.** ([`items.yml`](https://github.com/RockinChaos/ItemJoin/files/8839717/items.zip))

**Comment by TeQTabanca** [comment]
**Additionally if I turn on "Dynamic" Feature "Animate" is automatically turned on**

**Comment by TeQTabanca** [comment]
**In addition, I discovered another bug. if I set 2 different items to slot 4 of the single slot and make their worlds x(Main World) and z(different) if I exit and re-enter world z, the item of world z will still remain in my inventory. When I noticed this error, I decided to downgrade (I'm on version 5.2.0)**

**Comment by RockinChaos** [comment]
I apologize for not responding. I see your messages and have been checking on each issue.
- That figures why I couldn't figure out the armor issue.
- Thank you! The items.yml helped immensely.
- Odd that's definitely a bug. The animate/dynamic features are shared at a point but dynamic is just a limited functionality of animate, so it should not allow animate to enable itself. I am checking on this now.
- I can't replicate the 20 tick seconds issue. Would it be possible to enable debugging in the config.yml to produce an error code you can provide?
- As for the last issue, I can't seem to replicate this. Would you be able to provide an EXACT copy of the specific items in question so I can test them independently?


Again sorry for the late response. I have a lot of bug fixes queued up to be pushed for a snapshot compile but I am still working on a few reworks of code--I should have it out relatively soon.

**Comment by TeQTabanca** [comment]
**It was giving the main menu item directly in the 5.2.0 version, so I switched to 5.2.0. The version in the video is b-832 ([Video and İtems.yml](https://github.com/RockinChaos/ItemJoin/files/8909690/Video.and.Items.yml.zip))**

**Comment by TeQTabanca** [comment]
**Now I tried the animate feature, it didn't give me an error. It's interesting. In addition, if I open the animate feature, open the name section, delete all the lines, press return and click the name section again, I cannot create a New name line. I need to save to config to create**

**Comment by TeQTabanca** [comment]
**By the way, I tried the animated feature, I set Name 1 to Test 40 ticks and Name 2 to Test2 100 ticks, but the item moves but the Name does not change, it remains Test**

**Comment by RockinChaos** [comment]
1.) Finally was able to replicate the ChestSort issue using the hotkeys you showed in the video, this has now been fixed. I was trying to make it where you can organize the bottom inventory while the menu is open but it turns out there is a bug with the older chestsort version that doesn't allow blocking of certain slots in the upper inventory. I have simply changed it to ALWAYS block any interaction with chestsort if the ItemJoin menu is open.
2.) Ah I understand now, you are asking for me to create a stackable plugin. I can look into this but I cannot guarantee any time frame or if I will do it at all due to my current workload. If I get some time this is something I will be interested in working on so I added it to my notes.
3.) Menu refresh glitch should now be fixed, if it happens again console will now output a stack trace for you to send to me.
4.) Replicated the animate itemflag issues in the menu and was able to provide a fix for it.
5.) I can't replicate the world-switch issue but it sounds like the Join trigger is being performed after the world-switch trigger so I added another world check to the join trigger. If this happens again, please enable debugging in the config.yml and send me the debug information when you join the server so I can view the trigger pattern.


Hopefully this addresses all your issues, this was a lot to go through haha.
Link; https://ci.craftationgaming.com/job/ItemJoin/835/
**Remember to remove your old ItemJoin.jar file**

**Comment by TeQTabanca** [comment]
**There is only one problem right now, when I save an item, it is a bit annoying to be on the last page (valid in the optional section) is there a chance to stay in the same place?**

https://user-images.githubusercontent.com/89253304/175806318-b1e0d71a-7c00-4285-b115-8c0dee50de8a.mp4

**Comment by TeQTabanca** [comment]
**Additionally, I recorded everything in one world. but if I enter a region and take its belongings and exit there and re-enter, the items in that region will remain on me. I also tried in B841 version but same. ([Video](https://github.com/RockinChaos/ItemJoin/files/9041801/Video.zip))**

**I turned on the debug feature, and when I joined the server, the following texts appeared on the console.**

> [21:51:05 WARN]: [ItemJoin_DEBUG] {ItemMap} TeqTabanca has performed A REGION trigger by teleporting.
> [21:51:06 WARN]: [ItemJoin_DEBUG] {ItemMap} TeqTabanca already has item: ana_menu_kitabi.
> [21:51:06 WARN]: [ItemJoin_DEBUG] {ItemMap} TeqTabanca has been given the item pvp_menusu_kitabi in the world [LOBI].
> [21:51:06 WARN]: [ItemJoin_DEBUG] {ItemMap} TeqTabanca already has item: ana_menu_kitabi.
> [21:51:06 WARN]: [ItemJoin_DEBUG] {ItemMap} TeqTabanca already has item: pvp_menusu_kitabi.

**Comment by RockinChaos** [comment]
> **Any chance of adding the "page-number: <-number->" attribute so that the "location" of the saved items does not change?**
> 
> **If you add this feature, the settings of the item will appear on that page even if it is at the bottom of the .yaml file. If there is no page limit, this feature can be adjusted. If there is a page limit, this feature may remain unadjustable. that is, if a server owner enters the items.yaml file and sets the page-number property to 1000 and uses the reload command from within the game, it will automatically be set to the default number.**

So I don't want to add any more lines to the items.yml as many people have a strict limit on file sizes.
However I went ahead and added an alternative, the items are now sorted alphabetically by their node name (not their display name). So as long as their node name does not change they will stay on the same page.

Hopefully, you like this change :)

Link; https://ci.craftationgaming.com/job/ItemJoin/842/
**Remember to remove your old ItemJoin.jar file**

> **Additionally, I recorded everything in one world. but if I enter a region and take its belongings and exit there and re-enter, the items in that region will remain on me. I also tried in B841 version but same. ([Video and items.yml](https://github.com/RockinChaos/ItemJoin/files/9041843/Video.and.items.yml.zip))**
> 
> **I turned on the debug feature, and when I joined the server, the following texts appeared on the console.**
> 
> > [21:51:05 WARN]: [ItemJoin_DEBUG] {ItemMap} TeqTabanca has performed A REGION trigger by teleporting.
> > [21:51:06 WARN]: [ItemJoin_DEBUG] {ItemMap} TeqTabanca already has item: ana_menu_kitabi.
> > [21:51:06 WARN]: [ItemJoin_DEBUG] {ItemMap} TeqTabanca has been given the item pvp_menusu_kitabi in the world [LOBI].
> > [21:51:06 WARN]: [ItemJoin_DEBUG] {ItemMap} TeqTabanca already has item: ana_menu_kitabi.
> > [21:51:06 WARN]: [ItemJoin_DEBUG] {ItemMap} TeqTabanca already has item: pvp_menusu_kitabi.

What is the plugin you are using to teleport you to spawn?
I would prefer to test with this plugin as it seems to be related to the player teleportation.

**Comment by TeQTabanca** [comment]
Honestly, I'm using 2 plugins. One is "EssentialsSpawn" and the other is "SpawnPlugin". The priority is the "EssentialsSpawn" plugin. Versions:
SpawnPlugin-1.0.3
EssentialsXSpawn-2.19.4

**Comment by TeQTabanca** [comment]
### When will this problem be solved at the latest? does it take so much time?

**Comment by RockinChaos** [comment]
Hi, I apologize that it is taking a bit. I just started college last week for my 2nd degree so the free time I have has been significantly reduced.
I have already identified the issue and it seems to be related to a bugfix I did that caused a rewrite in how the region triggers function, basically allowing them to work cross-worlds. The issue is the bugfix caused the problem you are reporting and to resolve the issue I have to rewrite the WorldGuard class again to accommodate for both issues. There's a lot of code that goes into making regions function for "every-case-scenarios" so rewriting the core functionality takes some time.

I am about **75% done** with the rewrite so expect a snapshot link soon.

Again I apologize for how long this is taking.

**Comment by RockinChaos** [comment]
Okay so I managed to fix the bug and it seems to be working on my end now using the items you provided.
You do need to make some modifications though, from the items in which regions are defined remove world-switch and gamemode-switch from the triggers. This is because it will cause the event to double-fire as any region trigger automatically handles these so specifying duplicates causes it to execute twice and will result in a similar bug as described in the video.

Snapshot that contains the bugfix; https://ci.craftationgaming.com/job/ItemJoin/843/
**Remember to remove your old ItemJoin.jar file**

Let me know!~

**Comment by TeQTabanca** [comment]
**I removed the gamemode-switch trigger. it works fine. For me, the gamemode-switch feature is also important. So you're going to rewrite the gamemode-switch trigger, right?**

**Comment by RockinChaos** [comment]
I don't think I understand, the gamemode-switch feature shouldn't be needed as the items with the region triggers already include this. I might misunderstand what you are saying, if you can clarify that would help.

**Comment by TeQTabanca** [comment]
**Required in PVP-PVE mode. I try to give players packaged weapons as there are modern weapons. So Ak-47, Glock-18, Karambit will run their weapons with a single command and their inventory will be deleted and the weapons will be in their inventory. The "gamemode-switch" trigger plays an important role, as the items given in the region will be deleted after the inventory is deleted. In other words, after the inventory is deleted, it will go to the first peace mode and then to the default mode, and the item given in the region will remain in the inventory again. That's why the gamemode-switch trigger is important.**

**Comment by TeQTabanca** [comment]
**In addition, I gave up on being one world. Because there is a plugin that saves inventory by worlds.**

**Comment by RockinChaos** [comment]
Ahhhh I see so it's basically like a per gamemode or per world inventory plugin.
Hmmm let me do some testing, this should be pretty easy to figure out.

**Comment by RockinChaos** [comment]
Okay so quick update, I have done some extensive testing for a while with region triggers and gamemode-switch. You should be able to specify both `GAMEMODE-SWITCH, REGION-ACCESS` or any other region trigger together without any issue. The secondary trigger is only executed if you specify world-switch as well so simply specifying gamemode-switch and a region trigger does not cause any issues that I can find.

No snapshot update is required, please let me know.

**Comment by TeQTabanca** [comment]
> Okay so quick update, I have done some extensive testing for a while with region triggers and gamemode-switch. You should be able to specify both `GAMEMODE-SWITCH, REGION-ACCESS` or any other region trigger together without any issue. The secondary trigger is only executed if you specify world-switch as well so simply specifying gamemode-switch and a region trigger does not cause any issues that I can find.
> 
> No snapshot update is required, please let me know.

So you mean should I use "`GAMEMODE-SWITCH, REGION-ACCESS, WORLD-SWITCH`" instead of "GAMEMODE-SWITCH, REGION-ACCESS"?

**Comment by RockinChaos** [comment]
no I mean you can use `GAMEMODE-SWITCH, REGION-ACCESS` instead of `REGION-ACCESS` as WORLD-SWITCH is already covered by the REGION triggers as they get executed when a player teleports aka switches worlds (even via portals).

So I am saying please test with `GAMEMODE-SWITCH, REGION-ACCESS` and let me know as this should cover your gamemode switching problems, I did some testing and it seems this does work as intended.

**Comment by TeQTabanca** [comment]
It's still giving.

### DEBUG:

> [07:24:15 INFO]: Teq Gun issued server command: /gamemode creative
> [07:24:15 WARN]: [ItemJoin_DEBUG] {ItemMap} Performed TeqTabanca LIMIT-SWITCH trigger.
> [07:24:15 WARN]: [ItemJoin_DEBUG] {ItemMap} TeqTabanca was given the main_menu_book item in the [LOBI] world.
> [07:24:15 WARNING]: [ItemJoin_DEBUG] {ItemMap} TeqTabanca was given the item [LOBI] pvp_menusu_book in the world.

**Comment by TeQTabanca** [comment]
**I tried the b844 version but nothing changed.**

> [09:12:15 WARN]: [ItemJoin_DEBUG] {ItemMap} TeqTabanca has performed the LIMIT-SWITCH trigger.
> [09:12:15 WARN]: [ItemJoin_DEBUG] {ItemMap} TeqTabanca has been given the item ana_menu_kitabi in the world [LOBI].
> [09:12:15 WARN]: [ItemJoin_DEBUG] {ItemMap} TeqTabanca has been given the item pvp_menusu_kitabi in the world [LOBI].

**Comment by RockinChaos** [comment]
Okay, after some extensive testing I was able to replicate the issue.
Some triggers were specifically designed to ignore the region entirely and gamemode-switch was one of those triggers.

I have simply made it so this trigger now respects the region boundaries.

Link; https://ci.craftationgaming.com/job/ItemJoin/845/
**Remember to remove your old ItemJoin.jar file**

**Comment by TeQTabanca** [comment]
**I tried it now and it works fine. If there is any other problem, I will write here.**

**Comment by TeQTabanca** [comment]
**There is one more problem. In the Enabled Regions section, X automatically selects the __global__ regions of other worlds while selecting the __global__ region of one world.**

https://user-images.githubusercontent.com/89253304/183104320-2716e995-a93b-4c32-9bb1-b9e3177e6fbb.mp4

**Comment by TeQTabanca** [comment]
> **There is one more problem. In the Enabled Regions section, X automatically selects the **global** regions of other worlds while selecting the **global** region of one world.**
> 
>  itemjoin.__global__.regions.problem.mp4

**In addition, they are selected in regions with the same region name.**

**Comment by TeQTabanca** [comment]
**I found 2 more problems but related to other plugins!**

### 1- If I Shift + Left or Right Click while trading, the item will be traded. (TradeMe plugin.)
[TRADE VİDEO](https://www.veed.io/view/5ab62fc5-bd31-40bf-af23-31f0f7e44cc4?sharingWidget=true)

### 2- Entering and exiting custom game mode. (Plugins with custom game mode.)
[CUSTOM GAME VİDEO](https://www.veed.io/view/3eff442a-7878-4a7f-b094-c4e63eee92aa?sharingWidget=true)

**Comment by RockinChaos** [comment]
Apologies, I am just approaching finals week so I have been pretty busy taking tests.

1.) I am working on the region issue.
2.) TradeMe issue is already confirmed as not-resolvable. It is their issue, not ItemJoin--they need to add an API event but unfortunately, my request is still unread which I submitted last year. Someone said they were able to resolve it using their blacklisting system but it has been a while since then.
3.) Custom Game Mode - Video is not available :(

**Comment by TeQTabanca** [comment]
> Apologies, I am just approaching finals week so I have been pretty busy taking tests.
> 
> 1.) I am working on the region issue. 2.) TradeMe issue is already confirmed as not-resolvable. It is their issue, not ItemJoin--they need to add an API event but unfortunately, my request is still unread which I submitted last year. Someone said they were able to resolve it using their blacklisting system but it has been a while since then. 3.) Custom Game Mode - Video is not available :(

**Good luck. I hope you get a good result.**

```
1) I turned on debug mode to look into this issue but it showed nothing. That's why I can't say anything.

2) I guess the only solution is to use the blacklist section.

3) Actually, I should have added it to sites like DropBox, but it never occurred to me.
```

> [17:51:50 INFO]: Test issued server command: /counterstrike join 0
> [17:51:50 WARN]: [ItemJoin_DEBUG] {ItemMap} Test has performed A REGION trigger by teleporting.
> [17:51:50 WARN]: [ItemJoin_DEBUG] {ItemMap} Test has performed the WORLD-SWITCH trigger.
> 
> [17:51:59 INFO]: Test issued server command: /counterstrike leave
> [17:51:59 WARN]: [ItemJoin_DEBUG] {ItemMap} Test has performed A REGION trigger by teleporting.
> [17:51:59 WARN]: [ItemJoin_DEBUG] {ItemMap} Test has performed the WORLD-SWITCH trigger.
> [17:51:59 WARN]: [ItemJoin_DEBUG] {ItemMap} Test has been given the item ana_menu_kitabi in the world [SUNUCUYA_GIRIS].

Reloaded!
**[CUSTOM GAME VIDEO](https://www.dropbox.com/s/mzh33d7mot2flfb/itemjoin-custom_gamemode-join-bug.mp4?dl=0)**

**Comment by RockinChaos** [comment]
Okay so;
1.) Fixed the region pane issue. Keep in mind though if you select a region say in world called spawn then select __Global__ in world_nether it will still automatically enable __Global__ in world because they share the same name (this is simply a WorldGuard limitation). However, if you are simply selecting only one region and its __Global__ it will properly enable the corresponding world.
Link; https://ci.craftationgaming.com/job/ItemJoin/848/
**Remember to remove your old ItemJoin.jar file**

2.) Custom Game Mode - I see the video, can you link me to the plugin in question? I can't seem to find the one in the video.

**Comment by TeQTabanca** [comment]
1- I tried and still have the same problem.

https://user-images.githubusercontent.com/89253304/187034127-84b0ad50-29f4-4363-b2f7-e8279ad21b0b.mp4


2- The old name of that plugin was "counterstrike" but they changed it to "cops and crims". Unfortunately, it also happens in "BattleRoyaleX" and "PartyGamesX" game modes. I guess it might be because the addon saves players' items when players enter the addon's Game mode.

3- There is one more problem. I have set a .gif file to the filled map material, but after I take the filled map using the /itemjoin get command, it looks like a photo. After typing the name of another photo and saving it, I take the filled map using the /item get command and the previously set photo appears.

https://user-images.githubusercontent.com/89253304/187034135-caf6f5c1-db16-4624-b7fd-644121bc79e8.mp4


4- When you delete an item, nothing appears in the main menu

https://user-images.githubusercontent.com/89253304/187034254-d7b38a43-2ff6-46f8-a01d-8dfea8859a36.mp4

.

**Comment by RockinChaos** [comment]
3.) Can you provide those image/gif files? I tried replicating this but it seems to work fine using my test files.

4.) In the video you deleted the only item, therefore no items should be displayed in the main menu?

**Comment by TeQTabanca** [comment]
> 3.) Can you provide those image/gif files? I tried replicating this but it seems to work fine using my test files.
> 
> 4.) In the video you deleted the only item, therefore no items should be displayed in the main menu?

3- By the way, because I adjusted the .gif video with paint.net, its animation was not visible. So the .gif animation works. I am sorry for this.The only problem now is if I put a photo or .gif video in the filled map material and save it, and then set a new image or .gif video and save it, it shows whichever image or .gif video was set first.

4- After I deleted the item, the items I set did not appear, I wanted to show it.

**Comment by TeQTabanca** [comment]
**I'm trying to make the identifier property, but when I save the item, the command I set is deleted. I looked at the wiki, there are winner-loser options, but after typing winner or loser, I save the item, but the command I set is deleted. Finally, do you have a chance to add `shooter` and `victim` command for `On-Hit` and `On-Damage` feature? In other words, the `shooter` feature is the commands to be executed for the player who causes damage when the player damages a player, and the `victim` feature is the commands to be executed for the damaged player when the player damages a player.**

https://user-images.githubusercontent.com/89253304/188333727-4191586d-a582-4f5b-8684-4c87acedf696.mp4

**Comment by TeQTabanca** [comment]
### I found another problem. When I close and save all the worlds, it goes back to how it was.

https://user-images.githubusercontent.com/89253304/193354518-d379b3b6-b5f6-4e01-b13d-4ca6bdd7237f.mp4

**Comment by RockinChaos** [comment]
Hi, I am terribly sorry about the delays. I haven't found an easy way to mass-update all the issues on GitHub.
I posted an announcement in the discord that clarifies what happened;
Currently, I do not have a computer to develop on as for some reason my desktop experienced a catastrophic failure where my drive died and I lost all my up-to-date files and something is wrong with my motherboard so I am working on fixing my desktop so I can get back into the swing of things.

I have a backup of my drive which is a little out of date but it should be able to get me started back on developing.
At the moment I have been developing on my phone which is pretty slow and tedious.

I should be able to be back up and running in the next week or so once I replace my motherboard.


So again I apologize, I am not ignoring you, just unable to easily reach out at the moment.

**Comment by TeQTabanca** [comment]
> Hi, I am terribly sorry about the delays. I haven't found an easy way to mass-update all the issues on GitHub. I posted an announcement in the discord that clarifies what happened; Currently, I do not have a computer to develop on as for some reason my desktop experienced a catastrophic failure where my drive died and I lost all my up-to-date files and something is wrong with my motherboard so I am working on fixing my desktop so I can get back into the swing of things.
> 
> I have a backup of my drive which is a little out of date but it should be able to get me started back on developing. At the moment I have been developing on my phone which is pretty slow and tedious.
> 
> I should be able to be back up and running in the next week or so once I replace my motherboard.
> 
> So again I apologize, I am not ignoring you, just unable to easily reach out at the moment.

**I understand. Even if you don't answer already, I check your plugin's build every week. If a new build is released, I try it immediately and let you know if the error is resolved.**

**Comment by RockinChaos** [comment]
Going to move this over to our Discord ticket as I keep getting confused about what we have already covered between the two conversations.
